newrelic/nr-labs-pathpoint

README.md
catalog/config.json
catalog/documentation.md
package-lock.json
package.json

Reverts newrelic/nr-labs-pathpoint#346

Revert "fix: update repo urls"

---

README.md
catalog/config.json
catalog/documentation.md
package-lock.json
package.json

Reverts newrelic/nr-labs-pathpoint#348

Revert "Revert "fix: update repo urls""

---

src/components/stages/index.js
src/queries/entities.js

fix: missing violations for workloads

---

src/constants/app.js

fix: add 30 min to polling intervals

---

src/components/flow/index.js
src/components/playback-bar/index.js

playback data fixes

---

src/components/stages/index.js

fix: cancel timeout on refetch and playback

---

nerdlets/home/index.js

fix: remove opening of product-tour on initial load

---

nerdlets/home/index.js
src/components/flow/index.js

fix: preview not working for empty flow

---

package-lock.json
package.json

fix: couple timepicker issues

---

src/components/flow/header.js
src/components/flow/index.js
src/components/playback-bar/index.js
src/utils/datetime.js

fix: display playback time window in place of current status

---

package-lock.json
package.json

fix: update nr-labs-component to use updated nrqleditor

---

src/components/stages/index.js
src/utils/alerts.js

fix: missing signal statuses for alerts

---

nerdlets/signal-selection/listing.js

fix: remove workload button in signal selection

---

nerdlets/home/index.js
src/constants/ui-content.js

fix: add help modal

---

src/components/stage/index.js

fix: move level button to bottom of stage

---

src/components/kpi-bar/index.js
src/components/stages/index.js
src/hooks/use-fetch-kpis/index.js

Fixes #413 
- Also includes a minor fix in the `Stages` component

fix: add polling for kpis

---

src/components/stages/index.js
src/queries/alert-conditions.js
src/utils/alerts.js

fix: batch fetch alert condition status

---

nerdlets/signal-selection/listing-table.js

fix: signal table select all

---

nerdlets/create-flow/blank.js
nerdlets/create-flow/import.js
nerdlets/create-flow/index.js
nerdlets/create-flow/styles.scss

fix: flow creation default account to flow list account picker

---

src/components/signal-tooltip/index.js
src/components/signal-tooltip/styles.scss
src/components/signals-grid-layout/index.js
src/components/styles.scss
src/constants/signals.js
src/constants/ui-content.js
src/queries/entities.js

fix: enhanced signal tooltip

---

src/components/signal-detail-sidebar/incidents.js

fix: update button in signal detail sidebar

---

src/components/stage/header.js
src/components/stage/styles.scss

fix: add link icon for stages with links

---

src/components/step-settings-modal/index.js

- fix for step settings where turning off weights was not being saved

fix: step settings weight not updated on changes

---

src/components/signal-detail-sidebar/index.js
src/components/signal-detail-sidebar/styles.scss

fix: display time period in sidebar when in playback

---

src/components/flow/index.js

- fixes issue where sidebar displays playback data even after exiting playback

fix: playback timewindow remains after exit

---

src/components/flow/header.js
src/components/flow/index.js
src/components/stage/index.js
src/components/stages/index.js

fix: add loading indicators

---

nerdlets/home/index.js
src/components/level/index.js

NOTE: Pushing a quick fix for when switching modes is breaking the app in React 18.
TODO: `Preview` button in EDIT mode needs to be fixed.

fix: force transition when switching modes

---

src/components/signal-detail-sidebar/incidents.js
src/components/signal-tooltip/index.js
src/utils/signal.js

- remove data-fetching in `SignalTooltip`
- instead get data from `SignalsContext`
- move calculation of incidents list to `utils/signal.js` so it can be shared among components

fix: get signal tooltip to use data from context

---

src/components/signal-tooltip/index.js
src/components/signals-grid-layout/index.js
src/components/stages/index.js
src/contexts/index.js
src/contexts/playback.js

- add a playback context to keep track of playback time windows
- update `SignalTooltip` to use playback time window when available - fixes issue where incidents wouldn't show up in tooltip while in playback

fix: missing incidents in tooltip on playback

---

docs/messages.json
src/components/flow/header.js
src/components/flow/index.js

- fixes issue where preview was not working in edit mode
- remove message about preview issue

fix: preview not working issue

---

package-lock.json
package.json
src/components/kpi-modal/delete.js
src/components/kpi-modal/index.js
src/components/kpi-modal/styles.scss
src/components/modal/styles.scss

- update version of `nr-labs-components` to include fixes made to `NrqlEditor`
- pass list of accounts to `NrqlEditor`
- style fix to `Modal` component to make dialog backdrop animatable
- other minor code clean-up in `KpiModal`

fix: nrql editor and other kpi modal issues

---

src/components/export-flow-modal/index.js

- removing a duplicate `JSON.stringify` in `ExportFlowModal`

fix: remove duplicate json stringify

---

src/components/stages/index.js
src/constants/entities.js
src/constants/index.js
src/utils/signal.js

fix: workloads not displaying status in playback

---

src/components/flow-settings-modal/index.js
src/components/flow-settings-modal/styles.scss
src/components/flow/index.js

Closes #507 
- also includes some minor refactoring in `EditFlowSettingsModal`

fix: refresh interval select not showing in flow settings

---

nerdlets/home/index.js
src/components/flow/index.js
src/components/playback-bar/index.js
src/components/stages/index.js

Added `urlState` parameters to persist in permalinks:
- **Flow**: unhealthy, critical, expand toggles
- **Playback**: toggle, timePicker, playhead increment

fix: additional urlState values for permalink generation

---

src/components/flow-settings-modal/index.js
src/components/flow-settings-modal/styles.scss

fix: add metadata to flow settings modal

---

src/components/edit-in-place/index.js
src/components/flow/header.js
src/components/kpi-modal/index.js
src/components/stage/header.js
src/components/step/header.js
src/constants/ui-content.js

fix: clear placeholder/default text on EditInPlace refs

---

src/components/stage-notify-modal/index.js

fix: add tooltip to missing signals names

---

src/components/level/index.js
src/components/stage/index.js
src/components/stages/index.js
src/components/step/index.js
src/components/step/styles.scss
src/constants/ui-content.js

fix: added switch to hide all signals in edit mode for a given flow

---

package-lock.json
package.json
src/hooks/use-fetch-kpis/index.js
src/utils/nrql.js

fix: allow nrql editor to accept new lines/tabs

---

src/components/kpi-bar/index.js
src/components/kpi-bar/styles.scss
src/utils/kpi.js

fix: kpis sync with time picker in playback mode

---

README.md
catalog/config.json
nerdlets/signal-selection/components/selected-signals.js
nerdlets/signal-selection/index.js

- includes other minor cleanup
Closes #591

fix: set max entities by type in signal selection
